# Generated by Django 5.0.1 on 2024-01-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
    ]
